import type { LevelConfig } from "./types"

export const LEVEL_COUNT = 15

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: "💻 BOOT SEQUENCE CORRUPTION",
    description: "The system won't start. Rearrange the boot code fragments to restore the initialization sequence. Watch for syntax errors!",
    difficulty: "Tutorial",
    puzzleType: "codeFragment",
    enemyCount: 0,
    timeLimit: 180,
    corruptionRate: 0.05,
    requiredScore: 1,
    corruptionType: "startup_failure",
  },
  {
    id: 2,
    name: "🔌 LOGIC CIRCUIT FAILURE",
    description: "Security sensors are malfunctioning. Fix the logic gates to restore the alarm system before intruders break through.",
    difficulty: "Easy",
    puzzleType: "logicGate",
    enemyCount: 1,
    timeLimit: 150,
    corruptionRate: 0.1,
    requiredScore: 2,
    corruptionType: "circuit_damage",
  },
  {
    id: 3,
    name: "🧠 MEMORY PATTERN RECOVERY",
    description: "Critical data fragments are scattered. Reconstruct the memory sequence to recover lost system configurations.",
    difficulty: "Easy",
    puzzleType: "memorySequence",
    enemyCount: 2,
    timeLimit: 120,
    corruptionRate: 0.15,
    requiredScore: 3,
    corruptionType: "memory_leak",
  },
  {
    id: 4,
    name: "🔄 SORTING ALGORITHM REPAIR",
    description: "Database records are in chaos. Restore the bubble sort algorithm to organize the corrupted data files.",
    difficulty: "Medium",
    puzzleType: "algorithmReconstruction",
    enemyCount: 2,
    timeLimit: 120,
    corruptionRate: 0.2,
    requiredScore: 5,
    corruptionType: "algorithm_decay",
  },
  {
    id: 5,
    name: "🖥️ TERMINAL EMERGENCY PROTOCOL",
    description: "System integrity compromised. Execute emergency commands through the terminal to stabilize the core.",
    difficulty: "Medium",
    puzzleType: "terminalHacking",
    enemyCount: 3,
    timeLimit: 90,
    corruptionRate: 0.25,
    requiredScore: 8,
    corruptionType: "kernel_breach",
  },
  {
    id: 6,
    name: "🌳 BINARY TREE RESTORATION",
    description: "File system hierarchy collapsed. Rebuild the binary tree structure to restore proper data organization.",
    difficulty: "Medium",
    puzzleType: "binaryTree",
    enemyCount: 3,
    timeLimit: 110,
    corruptionRate: 0.3,
    requiredScore: 12,
    corruptionType: "tree_corruption",
  },
  {
    id: 7,
    name: "🌐 NETWORK PATH RECONSTRUCTION",
    description: "Communication links severed. Navigate the corrupted network graph to restore connectivity between systems.",
    difficulty: "Hard",
    puzzleType: "graphTraversal",
    enemyCount: 4,
    timeLimit: 100,
    corruptionRate: 0.35,
    requiredScore: 15,
    corruptionType: "network_failure",
  },
  {
    id: 8,
    name: "🔑 HASH TABLE COLLISION RESOLUTION",
    description: "Data indexing system overloaded. Resolve hash collisions to prevent data loss and system crashes.",
    difficulty: "Hard",
    puzzleType: "hashTable",
    enemyCount: 4,
    timeLimit: 90,
    corruptionRate: 0.4,
    requiredScore: 18,
    corruptionType: "hash_breakdown",
  },
  {
    id: 9,
    name: "⚡ DYNAMIC PROGRAMMING OPTIMIZATION",
    description: "Recursive functions causing performance bottlenecks. Implement memoization to optimize the fibonacci sequence calculation.",
    difficulty: "Hard",
    puzzleType: "dynamicProgramming",
    enemyCount: 5,
    timeLimit: 85,
    corruptionRate: 0.45,
    requiredScore: 22,
    corruptionType: "recursion_bomb",
  },
  {
    id: 10,
    name: "📚 STACK OPERATIONS RECOVERY",
    description: "Function call stack corrupted. Restore proper stack operations to prevent program crashes.",
    difficulty: "Expert",
    puzzleType: "stackOverflow",
    enemyCount: 5,
    timeLimit: 95,
    corruptionRate: 0.5,
    requiredScore: 25,
    corruptionType: "stack_breach",
  },
  {
    id: 11,
    name: "🔗 LINKED DATA STRUCTURE REPAIR",
    description: "Data chains broken. Reconnect the linked list nodes to restore data integrity and prevent memory leaks.",
    difficulty: "Expert",
    puzzleType: "linkedListCorruption",
    enemyCount: 6,
    timeLimit: 90,
    corruptionRate: 0.55,
    requiredScore: 28,
    corruptionType: "pointer_chaos",
  },
  {
    id: 12,
    name: "🔁 RECURSIVE LOOP TERMINATION",
    description: "Infinite recursion detected. Break the recursive cycle in the factorial function before stack overflow.",
    difficulty: "Expert",
    puzzleType: "recursionLoop",
    enemyCount: 6,
    timeLimit: 85,
    corruptionRate: 0.6,
    requiredScore: 32,
    corruptionType: "recursion_hell",
  },
  {
    id: 13,
    name: "🗄️ DATABASE RELATIONSHIP RESTORATION",
    description: "Data relationships corrupted. Fix the SQL queries and table joins to restore database functionality.",
    difficulty: "Master",
    puzzleType: "databaseCorruption",
    enemyCount: 7,
    timeLimit: 100,
    corruptionRate: 0.65,
    requiredScore: 35,
    corruptionType: "db_meltdown",
  },
  {
    id: 14,
    name: "📡 NETWORK PROTOCOL LAYER RECOVERY",
    description: "Communication protocol stack failing. Rebuild each OSI layer to restore full network connectivity.",
    difficulty: "Master",
    puzzleType: "networkProtocol",
    enemyCount: 7,
    timeLimit: 95,
    corruptionRate: 0.7,
    requiredScore: 38,
    corruptionType: "protocol_decay",
  },
  {
    id: 15,
    name: "💀 SYSTEM CORE SINGULARITY",
    description: "All systems converging to a single point of failure. Master every algorithmic paradigm to escape the digital abyss.",
    difficulty: "Legendary",
    puzzleType: "multiAlgorithm",
    enemyCount: 8,
    timeLimit: 150,
    corruptionRate: 0.8,
    requiredScore: 42,
    corruptionType: "total_collapse",
  },
]
